[package]
name = "j_assembler"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
j_system_definition = {path = "../j_system_definition"}
regex = "1.5.5"
lazy_static = "1.4.0"