[package]
name = "j_interpreter"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
j_system_definition = {path = "../j_system_definition"}
clap = {version = "3.2.17", features = ["derive"]}